BangBangBwa/Backend

- build.gradle
- src/main/java/com/bangbangbwa/backend/domain/BasicController.java
- src/main/java/com/bangbangbwa/backend/global/error/GlobalExceptionHandler.java
- src/main/java/com/bangbangbwa/backend/global/error/exception/BusinessException.java
- src/main/java/com/bangbangbwa/backend/global/error/exception/ForbiddenException.java
- src/main/java/com/bangbangbwa/backend/global/error/exception/ServerException.java
- src/main/java/com/bangbangbwa/backend/global/error/exception/UnAuthenticatedException.java
- src/main/java/com/bangbangbwa/backend/global/error/type/ApiErrorType.java
- src/main/java/com/bangbangbwa/backend/global/response/ApiResponse.java
- 공통 응답 구현
- 공통 예외 핸들링
- build.gradle 버전 명시
<br/>
feature/BBB-2 -> develop
- CI/CD 파이프 라인 구축
<br/>
- [BBB-2](https://bangbangbwa.atlassian.net/browse/BBB-2)
<br/>
> [BBB-2] 공통 응답 및 예외 핸들링 처리 구현

- .github/workflows/workflow.dev.yml
- .github/workflows/workflow.feat.yml
- Dockerfile
- src/main/resources/application.yml
- [[BBB-3] 기능 개발 파이프라인 구축](https://github.com/BangBangBwa/Backend/commit/cf7871e854777cc5b6ca31f63d616e5068205e28)
- [[BBB-3] .gitkeep 파일 추가](https://github.com/BangBangBwa/Backend/commit/e104d2c9f55ebca343cfa49971490953fecb6954)
- [[BBB-3] 개발 서버 ci/cd 파이프라인 구축](https://github.com/BangBangBwa/Backend/commit/17a456e28ccda727321bb566fbff8f6c075c28fa)
- 문제 해결
- https://bangbangbwa.atlassian.net/wiki/x/EwAq
<br/>
feature/BBB-3 -> develop
- Swagger 설정
- 회원 관련 API 명세서 작성
- 소셜 로그인 / 회원가입 구현
<br/>
- https://bangbangbwa.atlassian.net/browse/BBB-3
<br/>
> [BBB-3] CI/CD 파이프 라인 구축

- build.gradle
- src/main/java/com/bangbangbwa/backend/domain/BasicApi.java
- src/main/java/com/bangbangbwa/backend/domain/BasicController.java
- src/main/java/com/bangbangbwa/backend/global/annotation/ApiCommonResponse.java
- src/main/java/com/bangbangbwa/backend/global/config/MyBatisConfig.java
- src/main/java/com/bangbangbwa/backend/global/config/SecurityConfig.java
- src/main/java/com/bangbangbwa/backend/global/config/SwaggerConfig.java
- src/main/resources/application.yml
- [[BBB-11] Swagger 설정](https://github.com/BangBangBwa/Backend/commit/eb20258e9c1fbe68f4b01caf3308137ed28459ef)
- [공통으로 사용되는 ApiResponse 커스텀 어노테이션으로 정의](https://github.com/BangBangBwa/Backend/commit/feac9e7d9c80c7e476b09ce5d5d3da08f0f75d9d)
- [Swagger 문서화 샘플 코드 추가](https://github.com/BangBangBwa/Backend/commit/075cdb8ce19aa26d5c5dca18876877a70dffba0d)
<br/>
feature/BBB-11 -> develop
- Swagger 화면
- 회원 관련 API 명세서 작성
- 소셜 로그인/회원가입 구현
<br/>
- https://bangbangbwa.atlassian.net/browse/BBB-11
<br/>
> [BBB-11] Swagger 설정

- src/main/java/com/bangbangbwa/backend/global/config/MyBatisConfig.java
- src/main/java/com/bangbangbwa/backend/global/config/SecurityConfig.java
- src/main/java/com/bangbangbwa/backend/global/config/log/CachingRequestWrapper.java
- src/main/java/com/bangbangbwa/backend/global/config/log/LogFilter.java
- src/main/java/com/bangbangbwa/backend/global/config/log/SqlLogInterceptor.java
- src/main/resources/logback-spring.xml
- src/test/resources/logback-spring-test.xml
- LogFilter 추가로 Request, Response 응답을 Filter를 활용해 확인할 수 있도록 함
현재는 별도의 Filter가 존재하지 않아 @Component 추가 해두었음
- SqlLogInterceptor , MyBatisConfig 추가로 Interceptor를 활용해 Sql Log를 확인할 수 있도록 함.
<br/>
ex) feature/BBB-26 -> develop
- 구글 로그인 리펙토링
<br/>
[https://bangbangbwa.atlassian.net/browse/BBB-26](url)
<br/>
> [BBB-26] 로깅

- src/main/java/com/bangbangbwa/backend/global/config/log/CachingRequestWrapper.java
- src/main/java/com/bangbangbwa/backend/global/config/log/LogFilter.java
- LogFilter Multipart 정보 로그 추가
- getParameterMap 코드 제거
<br/>
feature/BBB-27 -> develop
- 없음
<br/>
- https://bangbangbwa.atlassian.net/browse/BBB-27?atlOrigin=eyJpIjoiMTJiMGI1ODc2YWU1NDcwMGIwMmE5Zjg3ZDVjM2VkMTUiLCJwIjoiaiJ9
<br/>
> [BBB-27] LogFilter Multipart 로그 추가

- src/main/java/com/bangbangbwa/backend/domain/member/common/dto/MemberLoginDto.java
- src/main/java/com/bangbangbwa/backend/domain/member/common/dto/MemberSignupDto.java
- src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberApi.java
- src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberController.java
- src/main/java/com/bangbangbwa/backend/domain/member/service/MemberService.java
- src/main/java/com/bangbangbwa/backend/domain/oauth/service/OAuthService.java
- 회원가입 API Swagger 문서 수정
- 로그인 API Swagger 문서 정의
<br/>
feature/BBB-15 -> develop
- 회원가입
- 로그인
- 구글 로그인 비지니스 로직 구현
<br/>
- https://bangbangbwa.atlassian.net/browse/BBB-15
<br/>
> [BBB-15] 구글 회원가입 & 로그인 Swagger API 구현

- src/main/java/com/bangbangbwa/backend/domain/promotion/common/dto/PromotionBannerDto.java
- src/main/java/com/bangbangbwa/backend/domain/promotion/common/dto/PromotionStreamerDto.java
- src/main/java/com/bangbangbwa/backend/domain/promotion/controller/PromotionApi.java
- src/main/java/com/bangbangbwa/backend/domain/promotion/controller/PromotionController.java
- 메인(홍보)페이지 API 명세서 및 더미데이터 기반 API 작성
<br/>
feature/BBB-30 -> develop
<br/>
<br/>
<br/>
- https://bangbangbwa.atlassian.net/browse/BBB-30?atlOrigin=eyJpIjoiZmZhMTM2NTA5NWIyNDk5YmI3ODNjMGQzZDY3OGY4NWMiLCJwIjoiaiJ9
<br/>
> [BBB-30] 메인페이지 API 명세서 작성

- src/main/java/com/bangbangbwa/backend/domain/promotion/common/dto/PromotionBannerDto.java
- src/main/java/com/bangbangbwa/backend/domain/promotion/common/dto/PromotionStreamerDto.java
- Response 이름 수정 (Swagger)
<br/>
feature/BBB-30 -> develop
<br/>
- https://bangbangbwa.atlassian.net/browse/BBB-30
<br/>
> [BBB-30] 메인페이지 API 명세서 작성 - Response 이름 수정

- src/main/java/com/bangbangbwa/backend/domain/sns/common/dto/GetFollowedLatestPostsDto.java
- src/main/java/com/bangbangbwa/backend/domain/sns/common/dto/GetPostDetailsDto.java
- src/main/java/com/bangbangbwa/backend/domain/sns/common/dto/GetPostListDto.java
- src/main/java/com/bangbangbwa/backend/domain/sns/controller/SnsController.java
- src/main/java/com/bangbangbwa/backend/global/util/randomValue/Language.java
- src/main/java/com/bangbangbwa/backend/global/util/randomValue/RandomValue.java
- src/main/java/com/bangbangbwa/backend/global/util/randomValue/RandomValueGenerator.java
- src/main/java/com/bangbangbwa/backend/global/util/randomValue/StringGenerator.java
- RandomValue 생성 코드 ( Language, RandomValue, RandomValueGenerator, StringGenerator ) 추가
- Sns 페이지 더미데이터 API 추가
<br/>
feature/BBB-36 -> develop
- Sns 페이지 API 명세서 작성
<br/>
[- [레포 이름 #이슈번호](이슈 주소)](https://bangbangbwa.atlassian.net/jira/software/projects/BBB/boards/1?selectedIssue=BBB-36)
<br/>
> [BBB-36] SNS페이지 더미데이터 API

- src/main/java/com/bangbangbwa/backend/domain/sns/common/dto/GetFollowedLatestPostsDto.java
- src/main/java/com/bangbangbwa/backend/domain/sns/common/dto/GetPostDetailsDto.java
- src/main/java/com/bangbangbwa/backend/domain/sns/common/dto/GetPostListDto.java
- src/main/java/com/bangbangbwa/backend/domain/sns/controller/SnsApi.java
- src/main/java/com/bangbangbwa/backend/domain/sns/controller/SnsController.java
- src/main/java/com/bangbangbwa/backend/global/util/randomValue/Language.java
- src/main/java/com/bangbangbwa/backend/global/util/randomValue/RandomValue.java
- src/main/java/com/bangbangbwa/backend/global/util/randomValue/RandomValueGenerator.java
- src/main/java/com/bangbangbwa/backend/global/util/randomValue/StringGenerator.java
- SNS 페이지 API 명세서 작성 및 적용
<br/>
feature/BBB-37 -> develop
- 카카오 , 네이버 로그인 적용
<br/>
[- [레포 이름 #이슈번호](이슈 주소)](https://bangbangbwa.atlassian.net/jira/software/projects/BBB/boards/1?selectedIssue=BBB-37)
<br/>
> [BBB-37] SNS 페이지 API 명세서 작성

- build.gradle
- src/main/java/com/bangbangbwa/backend/domain/member/business/MemberReader.java
- src/main/java/com/bangbangbwa/backend/domain/member/business/MemberValidator.java
- src/main/java/com/bangbangbwa/backend/domain/member/common/dto/MemberLoginDto.java
- src/main/java/com/bangbangbwa/backend/domain/member/common/dto/MemberSignupDto.java
- src/main/java/com/bangbangbwa/backend/domain/member/common/mapper/MemberMapper.java
- src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberApi.java
- src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberController.java
- src/main/java/com/bangbangbwa/backend/domain/member/exception/NotSignupMemberException.java
- src/main/java/com/bangbangbwa/backend/domain/member/exception/type/MemberErrorType.java
- src/main/java/com/bangbangbwa/backend/domain/member/repository/MemberRepository.java
- src/main/java/com/bangbangbwa/backend/domain/member/service/MemberService.java
- src/main/java/com/bangbangbwa/backend/domain/oauth/business/GoogleInfoProvider.java
- src/main/java/com/bangbangbwa/backend/domain/oauth/business/OAuthFeignManager.java
- src/main/java/com/bangbangbwa/backend/domain/oauth/business/OAuthInfoProvider.java
- src/main/java/com/bangbangbwa/backend/domain/oauth/business/feign/GoogleTokenFeign.java
- src/main/java/com/bangbangbwa/backend/domain/oauth/common/dto/GoogleTokenDto.java
- src/main/java/com/bangbangbwa/backend/domain/oauth/common/dto/OAuthInfoDto.java
- src/main/java/com/bangbangbwa/backend/domain/oauth/service/OAuthService.java
- src/main/java/com/bangbangbwa/backend/global/error/GlobalExceptionHandler.java
- src/main/java/com/bangbangbwa/backend/global/util/Base64Util.java
- src/main/resources/mybatis/map/member.xml
- [[BBB-15] 구글 로그인 / 비지니스 로직 - OAuthInfo 조회](https://github.com/BangBangBwa/Backend/commit/2b7db38fafc37030e7329c37efdc190d8ca20b4b)
- [[BBB-15] 구글 로그인 / 비지니스 로직 - 로그인](https://github.com/BangBangBwa/Backend/commit/35b53309c2df25f97b73f56d1755eee0625555f1)
<br/>
feature/BBB-15 -> develop
- 가입되지 않은 회원
- 회원가입 성공
- 회원가입 후 로그인 성공
- 랜덤 닉네임 생성 API 구현
- 랜덤 닉네임 생성 비지니스 로직 구현
- 닉네임 중복 확인 API 구현
- 닉네임 중복 확인 비지니스 로직 구현
<br/>
- https://bangbangbwa.atlassian.net/browse/BBB-15
<br/>
> [BBB-15] 구글 로그인 비지니스 로직 구현

- src/main/java/com/bangbangbwa/backend/domain/member/common/dto/MemberNicknameDto.java
- src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberApi.java
- src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberController.java
- src/main/java/com/bangbangbwa/backend/global/annotation/swagger/ApiResponse200.java
- 닉네임 관련 API 명세서 작성
<br/>
<br/>
<br/>
> [BBB-4] 닉네임 관련 API 명세서 작성

- src/main/java/com/bangbangbwa/backend/domain/tag/business/TagCreator.java
- src/main/java/com/bangbangbwa/backend/domain/tag/business/TagManager.java
- src/main/java/com/bangbangbwa/backend/domain/tag/business/TagReader.java
- src/main/java/com/bangbangbwa/backend/domain/tag/common/entity/Tag.java
- src/main/java/com/bangbangbwa/backend/domain/tag/repository/TagRepository.java
- src/main/resources/mybatis/map/tag.xml
- src/main/resources/schema.sql
- Tag 생성 및 반환 로직 추가
<br/>
feature/BBB-32 -> develop
- Tag 생성 및 반환 로직 테스트 코드 작성
<br/>
[https://bangbangbwa.atlassian.net/jira/software/projects/BBB/boards/1?selectedIssue=BBB-32](url)
<br/>
> [BBB-32] 태그 추가

- src/test/java/com/bangbangbwa/backend/global/test/ApplicationContextProvider.java
- src/test/java/com/bangbangbwa/backend/global/test/ContextLoadTest.java
- src/test/java/com/bangbangbwa/backend/global/test/ControllerTest.java
- src/test/java/com/bangbangbwa/backend/global/test/DatabaseCleaner.java
- src/test/java/com/bangbangbwa/backend/global/test/IntegrationTest.java
- src/test/java/com/bangbangbwa/backend/global/test/MyBatisTest.java
- src/test/java/com/bangbangbwa/backend/global/test/ServiceTest.java
- src/test/java/com/bangbangbwa/backend/global/util/randomValue/Language.java
- src/test/java/com/bangbangbwa/backend/global/util/randomValue/RandomValue.java
- src/test/java/com/bangbangbwa/backend/global/util/randomValue/RandomValueGenerator.java
- src/test/java/com/bangbangbwa/backend/global/util/randomValue/StringGenerator.java
- 테스트 코드 Util ( ApplicationContextProvider , ConteextLoadTest , ControllerTest, DatabaseCleaner, IntegrationTest, MyBatisTest, ServiceTest ) 추가
- 랜덤 값 생성 코드 ( Language, RandomValue, RandomValueGenerator, StringGenerator ) 추가
<br/>
feature/BBB-34 -> develop
- Tag 관련 코드 작성
<br/>
[- [레포 이름 #이슈번호](이슈 주소)](https://bangbangbwa.atlassian.net/jira/software/projects/BBB/boards/1?selectedIssue=BBB-34)
<br/>
> [BBB-34] 테스트 코드 Util 추가

- src/main/java/com/bangbangbwa/backend/domain/member/business/MemberReader.java
- src/main/java/com/bangbangbwa/backend/domain/member/business/MemberValidator.java
- src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberApi.java
- src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberController.java
- src/main/java/com/bangbangbwa/backend/domain/member/exception/type/DuplicatedNicknameException.java
- src/main/java/com/bangbangbwa/backend/domain/member/exception/type/MemberErrorType.java
- src/main/java/com/bangbangbwa/backend/domain/member/repository/MemberRepository.java
- src/main/java/com/bangbangbwa/backend/domain/member/service/MemberService.java
- src/main/resources/mybatis/map/member.xml
- 닉네임 중복 확인 비지니스 로직 구현
<br/>
feature/BBB-4 -> develop
- 닉네임 랜덤 생성 비지니스 로직 구현
<br/>
- https://bangbangbwa.atlassian.net/browse/BBB-4
<br/>
> [BBB-4] 닉네임 중복 확인 비지니스 로직 구현

- src/main/java/com/bangbangbwa/backend/global/config/WebConfig.java
- CORS 허용 정책  추가
<br/>
hotfix/cors -> develop
<br/>
<br/>
> [hotfix/cors] 임시 개발용 CORS 전체 허용

- src/main/java/com/bangbangbwa/backend/global/config/WebConfig.java
- 허용 도메인 * -> localhost:3000 변경
- 인증 정보 요청 허용
<br/>
hotfix/cors -> dev
<br/>
<br/>
> [hotfix/cors] 허용 도메인 변경 및 인증 정보 요청 허용

- src/main/java/com/bangbangbwa/backend/domain/member/business/MemberReader.java
- src/main/java/com/bangbangbwa/backend/domain/member/business/NicknameGenerator.java
- src/main/java/com/bangbangbwa/backend/domain/member/business/NicknameProvider.java
- src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberApi.java
- src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberController.java
- src/main/java/com/bangbangbwa/backend/domain/member/exception/MaxNicknameCountExceededException.java
- src/main/java/com/bangbangbwa/backend/domain/member/exception/NegativeNicknameCountException.java
- src/main/java/com/bangbangbwa/backend/domain/member/exception/NotExistsRemainNicknameException.java
- src/main/java/com/bangbangbwa/backend/domain/member/exception/type/MemberErrorType.java
- src/main/java/com/bangbangbwa/backend/domain/member/service/MemberService.java
- src/test/java/com/bangbangbwa/backend/domain/NicknameGeneratorTest.java
- 랜덤 닉네임 제공 비지니스 로직 구현
<br/>
feature/BBB-13 -> develop
```
[2024-10-29 19:31:11.239] [http-nio-8080-exec-3] [835f725c-8391-4f15-9e41-77eb537eaf6d] INFO  [ackend.global.config.log.LogFilter.logRequest:51 ] - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
[2024-10-29 19:31:11.239] [http-nio-8080-exec-3] [835f725c-8391-4f15-9e41-77eb537eaf6d] INFO  [ackend.global.config.log.LogFilter.logRequest:52 ] - Request : GET uri=[/api/v1/members/nicknames?count=1] content-type=[null], body=[null]
[2024-10-29 19:31:11.240] [http-nio-8080-exec-3] [835f725c-8391-4f15-9e41-77eb537eaf6d] DEBUG [.b.b.g.config.log.SqlLogInterceptor.intercept:50 ] - 
/*------------------------------ SQL LOG -----------------------------------*/
RESOURCE: file [C:\project\BBB\backend\build\resources\main\mybatis\map\member.xml …
```
> [BBB-13] 랜덤 닉네임 제공 비지니스 로직 구현

- src/main/java/com/bangbangbwa/backend/domain/promotion/business/BannerReader.java
- src/main/java/com/bangbangbwa/backend/domain/promotion/common/dto/PromotionBannerDto.java
- src/main/java/com/bangbangbwa/backend/domain/promotion/common/entity/Banner.java
- src/main/java/com/bangbangbwa/backend/domain/promotion/common/mapper/BannerMapper.java
- src/main/java/com/bangbangbwa/backend/domain/promotion/controller/PromotionController.java
- src/main/java/com/bangbangbwa/backend/domain/promotion/repository/BannerRepository.java
- src/main/java/com/bangbangbwa/backend/domain/promotion/service/BannerService.java
- src/main/resources/mybatis/map/banner.xml
- src/main/resources/schema.sql
- 배너 목록 조회 비지니스 로직 구현
<br/>
feature/BBB-43 -> develop
```
[2024-10-30 14:53:31.046] [http-nio-8080-exec-1] [1d64b14b-86f3-4fed-a16f-8291a93f8814] INFO  [ackend.global.config.log.LogFilter.logRequest:51 ] - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
[2024-10-30 14:53:31.046] [http-nio-8080-exec-1] [1d64b14b-86f3-4fed-a16f-8291a93f8814] INFO  [ackend.global.config.log.LogFilter.logRequest:52 ] - Request : GET uri=[/api/v1/promotions/banners] content-type=[null], body=[null]
[2024-10-30 14:53:31.059] [http-nio-8080-exec-1] [1d64b14b-86f3-4fed-a16f-8291a93f8814] DEBUG [.b.b.g.config.log.SqlLogInterceptor.intercept:50 ] - 
/*------------------------------ SQL LOG -----------------------------------*/
RESOURCE: file [C:\project\BBB\backend\build\resources\main\mybatis\map\banner.xml] …
```
> [BBB-43] 배너 목록 조회 비지니스 로직 구현

- src/main/java/com/bangbangbwa/backend/domain/member/common/enums/Role.java
- src/main/java/com/bangbangbwa/backend/domain/promotion/common/dto/PromotionStreamerDto.java
- src/main/java/com/bangbangbwa/backend/domain/promotion/common/enums/Platform.java
- src/main/java/com/bangbangbwa/backend/domain/promotion/controller/PromotionController.java
- Promotion Streamer 관련 Swagger 수정 작업
<br/>
feature/BBB-42 -> develop
<br/>
<br/>
> [BBB-42] 스트리머 더미 데이터 관련 수정

- src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberApi.java
- 토큰 재발급 API 명세서 추가
<br/>
feature/BBB-49 -> develop
- SNS 글쓰기
<br/>
- (https://bangbangbwa.atlassian.net/jira/software/projects/BBB/boards/1?selectedIssue=BBB-49)
<br/>
> [BBB-49] 토큰 재발급 API 명세서

- src/main/java/com/bangbangbwa/backend/domain/member/business/MemberProvider.java
- src/main/java/com/bangbangbwa/backend/domain/member/business/MemberValidator.java
- src/main/java/com/bangbangbwa/backend/domain/member/exception/AuthenticationNameNullException.java
- src/main/java/com/bangbangbwa/backend/domain/member/exception/AuthenticationNullException.java
- src/main/java/com/bangbangbwa/backend/domain/member/exception/DuplicatedNicknameException.java
- src/main/java/com/bangbangbwa/backend/domain/member/exception/NotParsedValueException.java
- src/main/java/com/bangbangbwa/backend/domain/member/exception/type/MemberErrorType.java
- src/main/java/com/bangbangbwa/backend/domain/sns/business/PostCreator.java
- src/main/java/com/bangbangbwa/backend/domain/sns/business/PostGenerator.java
- src/main/java/com/bangbangbwa/backend/domain/sns/business/PostParser.java
- src/main/java/com/bangbangbwa/backend/domain/sns/business/PostUpdater.java
- src/main/java/com/bangbangbwa/backend/domain/sns/common/dto/CreatePostDto.java
- src/main/java/com/bangbangbwa/backend/domain/sns/common/entity/Post.java
- src/main/java/com/bangbangbwa/backend/domain/sns/common/enums/PostType.java
- src/main/java/com/bangbangbwa/backend/domain/sns/common/mapper/PostMapper.java
- src/main/java/com/bangbangbwa/backend/domain/sns/controller/SnsController.java
- src/main/java/com/bangbangbwa/backend/domain/sns/exception/NoPostPermission.java
- src/main/java/com/bangbangbwa/backend/domain/sns/exception/type/PostErrorType.java
- src/main/java/com/bangbangbwa/backend/domain/sns/repository/PostRepository.java
- src/main/java/com/bangbangbwa/backend/domain/sns/service/SnsService.java
- src/main/resources/mybatis/map/post.xml
- src/main/resources/schema.sql
- SNS 글쓰기
- 사용자 ID 추출
- 인증/인가 오류 코드 추가
**공개/비공개 대상 및 이미지,첨부파일 관련 추가 작업 필요함**
<br/>
feature/BBB-48
- SNS 글쓰기 API 명세서 작성
<br/>
[- [레포 이름 #이슈번호](이슈 주소)](https://bangbangbwa.atlassian.net/jira/software/projects/BBB/boards/1?selectedIssue=BBB-48)
<br/>
> [BBB-48] SNS 글쓰기

- src/main/java/com/bangbangbwa/backend/global/config/WebConfig.java
- 긴급 수정 : CORS 관련 오류
preFlight 요청의 경우 "OPTIONS" 메서드로 요청이 들어오므로, OPTIONS 도 설정에 추가해줘야 함.
<br/>
hotfix/CORS -> develop
<br/>
<br/>
> [hotfix] CORS 오류 관련 수정

- src/main/java/com/bangbangbwa/backend/domain/sns/controller/SnsController.java
- 게시글 목록 조회 반환 값 고정값으로 변경
<br/>
feature/BBB-66 -> develop
- BBB-58 작업 마무리
<br/>
[- [레포 이름 #이슈번호](이슈 주소)](https://bangbangbwa.atlassian.net/jira/software/projects/BBB/boards/1?selectedIssue=BBB-66)
<br/>
> [BBB-66] 게시글 목록 조회 반환 값 고정값으로 변경

- src/main/java/com/bangbangbwa/backend/global/config/SecurityConfig.java
- SecurityCofig에 CORS 비활성화된 내용 수정함.
<br/>
hotfix/CORS -> develop
<br/>
<br/>
> [hotfix] CORS 오류 관련 SecurityConfig 수정

- src/main/java/com/bangbangbwa/backend/domain/member/common/dto/CommentDto.java
- src/main/java/com/bangbangbwa/backend/domain/member/common/dto/FollowerDto.java
- src/main/java/com/bangbangbwa/backend/domain/member/common/dto/PostDto.java
- src/main/java/com/bangbangbwa/backend/domain/member/common/dto/ProfileDto.java
- src/main/java/com/bangbangbwa/backend/domain/member/common/dto/SummaryDto.java
- src/main/java/com/bangbangbwa/backend/domain/member/common/entity/Follower.java
- src/main/java/com/bangbangbwa/backend/domain/member/common/entity/Member.java
- src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberApi.java
- src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberController.java
- src/main/java/com/bangbangbwa/backend/domain/member/service/MemberService.java
- src/main/java/com/bangbangbwa/backend/domain/promotion/common/dto/PromotionBannerDto.java
- src/main/java/com/bangbangbwa/backend/domain/promotion/common/dto/PromotionStreamerDto.java
- src/main/java/com/bangbangbwa/backend/domain/promotion/common/mapper/BannerMapper.java
- src/main/java/com/bangbangbwa/backend/domain/promotion/controller/PromotionController.java
- src/main/java/com/bangbangbwa/backend/domain/promotion/service/BannerService.java
- src/test/java/com/bangbangbwa/backend/domain/member/controller/MemberControllerTest.java
- src/test/java/com/bangbangbwa/backend/domain/member/service/MemberServiceTest.java
- src/test/java/com/bangbangbwa/backend/global/test/ControllerTest.java
- 마이페이지 조회 기본 코드 작성
- API 명세서 작성
- 더미데이터 API 생성
- 테스트코드 기본 코드 작성
- BBB-30은 이전에 작성했던 부분인데 Swagger 템플릿 컨밴션을 위해 일부 수정했습니다.
- feature/BBB-73 -> dev
- 테스트코드 작성 (TDD 기반)
- Service/Business/Repository 로직 작성
- https://bangbangbwa.atlassian.net/browse/BBB-73?atlOrigin=eyJpIjoiMDBjZmEyNzM1NTZhNDYyNTk0MjU3Mzk1Zjc5MjA5OTIiLCJwIjoiaiJ9
> [BBB-73] 마이페이지 조회 API 추가

- src/main/java/com/bangbangbwa/backend/domain/sns/common/dto/CreatePostDto.java
- src/main/java/com/bangbangbwa/backend/domain/sns/controller/SnsApi.java
- 댓글 작성 API 명세서 추가
<br/>
feature/BBB-77 -> develop
- 계정 등업 승인 API 명세서 작성
<br/>
[- [레포 이름 #이슈번호](이슈 주소)](https://bangbangbwa.atlassian.net/jira/software/projects/BBB/boards/1?selectedIssue=BBB-72)
<br/>
> [BBB-77] 댓글 작성 API 명세서 작성

- src/main/java/com/bangbangbwa/backend/domain/sns/common/dto/CreatePostDto.java
- src/main/java/com/bangbangbwa/backend/domain/sns/controller/SnsApi.java
- 게시글 작성 API 명세서 추가
<br/>
feature/BBB-55 -> develop
- 댓글 작성 API 명세서 추가
<br/>
[- [레포 이름 #이슈번호](이슈 주소)](https://bangbangbwa.atlassian.net/jira/software/projects/BBB/boards/1?selectedIssue=BBB-55)
<br/>
> [BBB-55] 글쓰기 API 명세서 작성

- src/main/java/com/bangbangbwa/backend/domain/member/business/MemberReader.java
- src/main/java/com/bangbangbwa/backend/domain/member/common/mapper/MemberMapper.java
- src/main/java/com/bangbangbwa/backend/domain/member/exception/type/EmptyNicknameException.java
- src/main/java/com/bangbangbwa/backend/domain/member/exception/type/MemberErrorType.java
- src/main/java/com/bangbangbwa/backend/domain/member/repository/MemberRepository.java
- src/main/java/com/bangbangbwa/backend/domain/sns/common/dto/SearchMemberDto.java
- src/main/java/com/bangbangbwa/backend/domain/sns/controller/SnsController.java
- src/main/java/com/bangbangbwa/backend/domain/sns/service/SnsService.java
- src/main/resources/mybatis/map/member.xml
- 사용자 닉네임 검색 ( 글자 별 )
- feature/BBB-77 -> develop
- API 명세서 작성
- https://bangbangbwa.atlassian.net/jira/software/projects/BBB/boards/1?selectedIssue=BBB-77
> [BBB-77] 사용자 닉네임 검색

- src/main/java/com/bangbangbwa/backend/domain/sns/business/PostProvider.java
- src/main/java/com/bangbangbwa/backend/domain/sns/business/PostReader.java
- src/main/java/com/bangbangbwa/backend/domain/sns/common/dto/GetPostListDto.java
- src/main/java/com/bangbangbwa/backend/domain/sns/common/entity/Post.java
- src/main/java/com/bangbangbwa/backend/domain/sns/common/mapper/PostMapper.java
- src/main/java/com/bangbangbwa/backend/domain/sns/controller/SnsController.java
- src/main/java/com/bangbangbwa/backend/domain/sns/repository/PostRepository.java
- src/main/java/com/bangbangbwa/backend/domain/sns/service/SnsService.java
- src/main/resources/mybatis/map/post.xml
- SNS 일반 모드 게시물 목록 조회
- feature/BBB-78 -> dev
- API 명세서
- SNS 방송 모드 게시물 목록 조회
- https://bangbangbwa.atlassian.net/jira/software/projects/BBB/boards/1?selectedIssue=BBB-78
> [BBB-78] 일반 모드 게시물 목록 조회

- src/main/java/com/bangbangbwa/backend/domain/member/business/MemberCreator.java
- src/main/java/com/bangbangbwa/backend/domain/member/business/MemberTagRelation.java
- src/main/java/com/bangbangbwa/backend/domain/member/common/dto/MemberSignupDto.java
- src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberController.java
- src/main/java/com/bangbangbwa/backend/domain/member/repository/MemberRepository.java
- src/main/java/com/bangbangbwa/backend/domain/member/service/MemberService.java
- src/main/resources/mybatis/map/memberTag.xml
- src/main/resources/schema.sql
- 회원가입 시 관심태그 등록할 수 있도록 비지니스 로직 추가
- feature/BBB-46 -> develop
```sql
[2024-11-22 21:54:11.170] [http-nio-8080-exec-10] [6ed4c90c-692a-4a5f-9a03-e13fab7f6b02] INFO  [ackend.global.config.log.LogFilter.logRequest:51 ] - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
[2024-11-22 21:54:11.170] [http-nio-8080-exec-10] [6ed4c90c-692a-4a5f-9a03-e13fab7f6b02] INFO  [ackend.global.config.log.LogFilter.logRequest:52 ] - Request : POST uri=[/api/v1/members/GOOGLE] content-type=[multipart/form-data; boundary=----WebKitFormBoundaryhfq73vDUsYlhPzJ1], body=[null]
[2024-11-22 21:54:11.170] [http-nio-8080-exec-10] [6ed4c90c-692a-4a5f-9a03-e13fab7f6b02] INFO  [ig.log.LogFilter.lambda$logMultipartRequest$1:75 ] - Form Field - Name: file, Value: []
[2024-11-22 21:54:11.170] [http-nio-8080-exec-10] …
```
> [BBB-46] 회원 관심태그 등록 비지니스 로직 추가

- src/main/java/com/bangbangbwa/backend/domain/member/business/MemberProvider.java
- src/main/java/com/bangbangbwa/backend/domain/promotion/business/StreamerReader.java
- src/main/java/com/bangbangbwa/backend/domain/promotion/repository/StreamerRepository.java
- src/main/java/com/bangbangbwa/backend/domain/sns/business/PostReader.java
- src/main/java/com/bangbangbwa/backend/domain/sns/common/dto/GetLatestPostsDto.java
- src/main/java/com/bangbangbwa/backend/domain/sns/common/dto/GetPostDetailsDto.java
- src/main/java/com/bangbangbwa/backend/domain/sns/common/mapper/PostMapper.java
- src/main/java/com/bangbangbwa/backend/domain/sns/controller/SnsApi.java
- src/main/java/com/bangbangbwa/backend/domain/sns/controller/SnsController.java
- src/main/java/com/bangbangbwa/backend/domain/sns/repository/PostRepository.java
- src/main/java/com/bangbangbwa/backend/domain/sns/service/SnsService.java
- src/main/java/com/bangbangbwa/backend/domain/streamer/common/business/DailyMessageGenerator.java
- src/main/java/com/bangbangbwa/backend/domain/streamer/common/business/DailyMessageReader.java
- src/main/java/com/bangbangbwa/backend/domain/streamer/common/exception/NotFoundStreamerException.java
- src/main/java/com/bangbangbwa/backend/domain/streamer/common/exception/type/StreamerErrorType.java
- src/main/java/com/bangbangbwa/backend/domain/streamer/repository/DailyMessageRepository.java
- src/main/java/com/bangbangbwa/backend/domain/streamer/service/DailyMessageService.java
- src/main/resources/data.sql
- src/main/resources/mybatis/map/post.xml
- src/main/resources/mybatis/map/streamer.xml
- src/main/resources/schema.sql
- 방송인 최신 글 표시
- 오늘의 한 마디 streamer 관련 작업
- 게시글 상세 조회 title 값과 profile 값이 반대로 매핑 되는 오류 수정
- feature/BBB-81 -> dev
- API 명세서
- 팔로우 관련 작업
- https://bangbangbwa.atlassian.net/jira/software/projects/BBB/boards/1?selectedIssue=BBB-81
> [BBB-81] 방송인 최신 글 표시

- src/test/java/com/bangbangbwa/backend/global/util/randomValue/RandomString.java
- src/test/java/com/bangbangbwa/backend/global/util/randomValue/RandomStringGenerator.java
- RandomString과 RandomStringGenerator 클래스를 도입하여 커스텀 랜덤 문자열 생성을 가능하게 합니다. 이 클래스들은 빌더 패턴을 사용하여 대문자, 소문자, 숫자, 특수문자 및 길이 제한과 같은 지정된 속성을 가진 문자열을 생성하는 유연한 방법을 제공합니다.
- RandomStringGenerator를 제 나름대로의 해석과 방향성으로 한 번 만들어보았습니다.
- feature/BBB-86-fix-Zeeeen0 -> feature/BBB-86
> [BBB-86-fix] 랜덤 문자열 생성을 위한 유틸리티 클래스 추가

- src/main/java/com/bangbangbwa/backend/domain/sns/common/dto/GetPostDetailsDto.java
- src/main/java/com/bangbangbwa/backend/domain/sns/controller/SnsController.java
- src/main/resources/mybatis/map/post.xml
- src/test/java/com/bangbangbwa/backend/domain/sns/controller/SnsIntegrationTest.java
- 게시물 상세 조회시 팔로우 여부 함께 반환
- feature/BBB-92 -> dev
- 일반/방송인 게시물 목록 조회 통합
- https://bangbangbwa.atlassian.net/jira/software/projects/BBB/boards/1?selectedIssue=BBB-92
> [BBB-92] 게시물 상세 조회 팔로우 여부 반환

- src/main/java/com/bangbangbwa/backend/domain/member/business/MemberProvider.java
- src/main/java/com/bangbangbwa/backend/domain/member/common/entity/Member.java
- src/main/java/com/bangbangbwa/backend/domain/member/common/enums/Role.java
- src/main/java/com/bangbangbwa/backend/domain/sns/business/PostTypeProvider.java
- src/main/java/com/bangbangbwa/backend/domain/sns/controller/SnsController.java
- src/main/java/com/bangbangbwa/backend/domain/sns/service/SnsService.java
- src/main/java/com/bangbangbwa/backend/domain/streamer/controller/StreamerController.java
- src/test/java/com/bangbangbwa/backend/domain/sns/controller/SnsIntegrationTest.java
- Role GUEST 추가
- 방송인 게시물 목록 조회 제거
- 일반/방송인 게시물 목록 조회 통합
- feature/BBB-93 -> dev
- 게시물 상세 조회 존재하지 않는 게시물일 경우 예외 처리
- https://bangbangbwa.atlassian.net/jira/software/projects/BBB/boards/1?selectedIssue=BBB-93
> [BBB-93] 일반/방송인 게시물 목록 조회 통합

- src/main/java/com/bangbangbwa/backend/domain/member/business/MemberProvider.java
- src/main/java/com/bangbangbwa/backend/domain/member/business/MemberReader.java
- src/main/java/com/bangbangbwa/backend/domain/member/business/MemberValidator.java
- src/main/java/com/bangbangbwa/backend/domain/member/common/dto/SummaryDto.java
- src/main/java/com/bangbangbwa/backend/domain/member/common/entity/Member.java
- src/main/java/com/bangbangbwa/backend/domain/member/common/mapper/SummaryMapper.java
- src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberController.java
- src/main/java/com/bangbangbwa/backend/domain/member/repository/MemberRepository.java
- src/main/java/com/bangbangbwa/backend/domain/member/service/MemberService.java
- src/main/java/com/bangbangbwa/backend/domain/promotion/common/entity/Streamer.java
- src/main/java/com/bangbangbwa/backend/domain/promotion/repository/StreamerRepository.java
- src/main/resources/data.sql
- src/main/resources/mybatis/map/member.xml
- src/main/resources/mybatis/map/streamer.xml
- src/main/resources/schema.sql
- src/test/java/com/bangbangbwa/backend/domain/member/MemberIntegrationTest.java
- src/test/java/com/bangbangbwa/backend/domain/member/MemberProfileIntegrationTest.java
- src/test/java/com/bangbangbwa/backend/domain/member/MemberSummaryIntegrationTest.java
- getProfile, getSummary 로직 구현
- feature/BBB-75 -> develop
- 기타 마이페이지 조회 API 개발
- platforms, tags 리스트 처리
- JIRA BBB-75
> [BBB-75] 마이페이지 - 프로필 정보 조회, 요약 조회 비즈니스 로직 구현

- src/main/java/com/bangbangbwa/backend/domain/sns/business/ReportCommentCreator.java
- src/main/java/com/bangbangbwa/backend/domain/sns/business/ReportCommentGenerator.java
- src/main/java/com/bangbangbwa/backend/domain/sns/business/ReportCommentParser.java
- src/main/java/com/bangbangbwa/backend/domain/sns/business/ReportCommentReader.java
- src/main/java/com/bangbangbwa/backend/domain/sns/business/ReportCommentUpdater.java
- src/main/java/com/bangbangbwa/backend/domain/sns/business/ReportValidator.java
- src/main/java/com/bangbangbwa/backend/domain/sns/common/dto/ReportCommentDto.java
- src/main/java/com/bangbangbwa/backend/domain/sns/common/entity/Comment.java
- src/main/java/com/bangbangbwa/backend/domain/sns/common/entity/ReportComment.java
- src/main/java/com/bangbangbwa/backend/domain/sns/common/mapper/ReportCommentMapper.java
- src/main/java/com/bangbangbwa/backend/domain/sns/controller/SnsController.java
- src/main/java/com/bangbangbwa/backend/domain/sns/repository/ReportCommentRepository.java
- src/main/java/com/bangbangbwa/backend/domain/sns/service/SnsService.java
- src/main/resources/mybatis/map/comment.xml
- src/main/resources/mybatis/map/reportComment.xml
- src/main/resources/schema.sql
- src/test/java/com/bangbangbwa/backend/domain/sns/controller/SnsIntegrationTest.java
- 댓글 신고
- feature/BBB-94 -> dev
- 방송인 최신 글 조회 streamerId -> memberId 반환
- https://bangbangbwa.atlassian.net/jira/software/projects/BBB/boards/1?selectedIssue=BBB-94
> [BBB-94] 댓글 신고

- src/main/java/com/bangbangbwa/backend/domain/tag/business/TagReader.java
- src/main/java/com/bangbangbwa/backend/domain/tag/common/dto/TagListDto.java
- src/main/java/com/bangbangbwa/backend/domain/tag/controller/TagApi.java
- src/main/java/com/bangbangbwa/backend/domain/tag/controller/TagController.java
- src/main/java/com/bangbangbwa/backend/domain/tag/repository/TagRepository.java
- src/main/java/com/bangbangbwa/backend/domain/tag/service/TagService.java
- src/main/resources/data.sql
- src/main/resources/mybatis/map/tag.xml
- 태그 목록 조회 API 및 비지니스 로직 구현
- feature/BBB-97 -> dev
```sql
[2024-12-02 21:27:38.748] [http-nio-8080-exec-3] [d73898cb-04c1-44f5-a326-67ea54a792a5] INFO  [ackend.global.config.log.LogFilter.logRequest:51 ] - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
[2024-12-02 21:27:38.748] [http-nio-8080-exec-3] [d73898cb-04c1-44f5-a326-67ea54a792a5] INFO  [ackend.global.config.log.LogFilter.logRequest:52 ] - Request : GET uri=[/api/v1/tags?tagWord=%EC%9E%A5] content-type=[null], body=[null]
[2024-12-02 21:27:38.749] [http-nio-8080-exec-3] [d73898cb-04c1-44f5-a326-67ea54a792a5] DEBUG [.b.b.g.config.log.SqlLogInterceptor.intercept:50 ] - 
/*------------------------------ SQL LOG -----------------------------------*/
RESOURCE: file [C:\project\BBB\backend\build\resources\main\mybatis\map\tag.xml] …
```
> [BBB-97] 태그 목록 조회 API 구현

- src/main/java/com/bangbangbwa/backend/domain/member/business/MemberProvider.java
- src/main/java/com/bangbangbwa/backend/domain/member/common/dto/SummaryDto.java
- src/main/java/com/bangbangbwa/backend/domain/member/service/MemberService.java
- src/main/java/com/bangbangbwa/backend/domain/promotion/business/StreamerReader.java
- src/main/java/com/bangbangbwa/backend/domain/promotion/repository/StreamerRepository.java
- src/main/resources/mybatis/map/member.xml
- src/main/resources/mybatis/map/streamer.xml
- src/test/java/com/bangbangbwa/backend/domain/member/MemberProfileIntegrationTest.java
- src/test/java/com/bangbangbwa/backend/global/util/randomValue/RandomString.java
- src/test/java/com/bangbangbwa/backend/global/util/randomValue/RandomStringGenerator.java
- getSummary 플랫폼 추가
- feature/BBB-75 -> develop
- getSummary 테스트코드 추가
- 게시글 목록 조회
- 댓글 목록 조회
- 팔로우/언팔로우
- 관심분야/방송분야 등록/삭제
- 플랫폼 등록/삭제
- 게시글 고정(Pin) 등록/삭제
- 이미지 포함여부, 동영상 포함여부 관리
> [BBB-75] 마이페이지 조회 getSummary 플랫폼 추가

- src/main/java/com/bangbangbwa/backend/domain/member/business/NicknameGenerator.java
- src/main/java/com/bangbangbwa/backend/domain/member/common/dto/MemberNicknameDto.java
- src/main/java/com/bangbangbwa/backend/domain/member/common/dto/MemberSignupDto.java
- src/main/java/com/bangbangbwa/backend/domain/member/common/entity/Member.java
- src/main/java/com/bangbangbwa/backend/domain/member/common/mapper/MemberMapper.java
- src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberApi.java
- src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberController.java
- src/main/java/com/bangbangbwa/backend/domain/member/service/MemberService.java
- src/main/resources/mybatis/map/member.xml
- src/main/resources/schema.sql
- 동의 항목 추가
- 랜덤 닉네임 생성 로직 수정
- AS-IS : count 매개변수로 닉네임 집합 반환.
- TO-BE : 1개의 닉네임 반환.
- feature/BBB-99 -> develop
- 네이버 로그인 관련 수정 사항 수정
- https://bangbangbwa.atlassian.net/browse/BBB-99
> [BBB-99] 회원가입 도메인 관련 수정사항 수정

- src/main/java/com/bangbangbwa/backend/domain/member/business/FollowReader.java
- src/main/java/com/bangbangbwa/backend/domain/member/common/dto/FollowDto.java
- src/main/java/com/bangbangbwa/backend/domain/member/common/dto/FollowerDto.java
- src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberApi.java
- src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberController.java
- src/main/java/com/bangbangbwa/backend/domain/member/repository/FollowRepository.java
- src/main/java/com/bangbangbwa/backend/domain/member/service/MemberService.java
- src/main/resources/mybatis/map/follow.xml
- src/test/java/com/bangbangbwa/backend/domain/member/MemberTest.java
- src/test/java/com/bangbangbwa/backend/domain/member/repository/FollowRepositoryTest.java
- 팔로워 목록 조회
- feature/BBB-109 -> dev
- 팔로우 추가/삭제
- https://bangbangbwa.atlassian.net/jira/software/projects/BBB/boards/1?selectedIssue=BBB-109
> [BBB-109] 팔로우/팔로워 목록 조회

- src/main/java/com/bangbangbwa/backend/domain/member/common/dto/PostDto.java
- src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberController.java
- src/main/java/com/bangbangbwa/backend/domain/member/service/MemberService.java
- src/main/java/com/bangbangbwa/backend/domain/sns/business/PostReader.java
- src/main/java/com/bangbangbwa/backend/domain/sns/common/entity/Post.java
- src/main/java/com/bangbangbwa/backend/domain/sns/common/mapper/PostMapper.java
- src/main/java/com/bangbangbwa/backend/domain/sns/repository/PostRepository.java
- src/main/resources/mybatis/map/post.xml
- src/main/resources/schema.sql
- src/test/java/com/bangbangbwa/backend/domain/member/MemberTest.java
- src/test/java/com/bangbangbwa/backend/domain/sns/repository/PostRepositoryTest.java
- 게시물 테이블 pinned (고정여부) 컬럼 추가
- 게시물 목록 조회
- feature/BBB-108 -> dev
- 게시물 고정 설정/해제
- https://bangbangbwa.atlassian.net/jira/software/projects/BBB/boards/1?selectedIssue=BBB-108
> [BBB-108] 게시물 목록 조회

- src/main/java/com/bangbangbwa/backend/domain/admin/common/dto/GetPendingMembers.java
- src/main/java/com/bangbangbwa/backend/domain/admin/controller/AdminController.java
- src/main/java/com/bangbangbwa/backend/domain/admin/service/AdminService.java
- src/main/java/com/bangbangbwa/backend/domain/streamer/common/business/PendingStreamerReader.java
- src/main/java/com/bangbangbwa/backend/domain/streamer/repository/PendingStreamerRepository.java
- src/main/resources/mybatis/map/pendingStreamer.xml
- src/test/java/com/bangbangbwa/backend/domain/streamer/common/business/PendingStreamerReaderTest.java
- 관리자 등업 요청 대기 중인 멤버 조회
- feature/BBB-110 -> dev
- 모든 게시물 조회
- https://bangbangbwa.atlassian.net/jira/software/projects/BBB/boards/1?selectedIssue=BBB-110
> [BBB-110] 등업 대기 요청 조회

- src/main/java/com/bangbangbwa/backend/domain/promotion/business/RandomStreamerProvider.java
- src/main/java/com/bangbangbwa/backend/domain/promotion/business/StreamerParser.java
- src/main/java/com/bangbangbwa/backend/domain/promotion/common/mapper/StreamerInterestedListMapper.java
- src/main/java/com/bangbangbwa/backend/domain/promotion/common/mapper/StreamerMapper.java
- src/main/java/com/bangbangbwa/backend/domain/promotion/controller/PromotionController.java
- src/main/java/com/bangbangbwa/backend/domain/promotion/repository/StreamerRepository.java
- src/main/java/com/bangbangbwa/backend/domain/promotion/service/StreamerService.java
- src/main/java/com/bangbangbwa/backend/domain/tag/business/TagReader.java
- src/main/java/com/bangbangbwa/backend/domain/tag/common/dto/TagDto.java
- src/main/java/com/bangbangbwa/backend/domain/tag/repository/TagRepository.java
- src/main/java/com/bangbangbwa/backend/global/config/SecurityConfig.java
- src/main/resources/data.sql
- src/main/resources/mybatis/map/streamer.xml
- src/main/resources/mybatis/map/tag.xml
- 홍보 스트리머 랜덤 조회 API 구현
- feature/BBB-47 -> dev
- 내 게시글 삭제/수정 API
- 내 게시글을 본 방송인 목록 조회 API
- 댓글 및 대댓글 조회 API 구현
- https://bangbangbwa.atlassian.net/browse/BBB-47
- https://bangbangbwa.atlassian.net/browse/BBB-101
> [BBB-47] 홍보 스트리머 랜덤 조회 API 구현

- src/main/java/com/bangbangbwa/backend/domain/member/common/dto/TogglePostPinDto.java
- src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberController.java
- src/main/java/com/bangbangbwa/backend/domain/member/service/MemberService.java
- src/main/java/com/bangbangbwa/backend/domain/sns/business/PostReader.java
- src/main/java/com/bangbangbwa/backend/domain/sns/business/PostUpdater.java
- src/main/java/com/bangbangbwa/backend/domain/sns/business/PostValidator.java
- src/main/java/com/bangbangbwa/backend/domain/sns/exception/MaxPinnedPostsExceededException.java
- src/main/java/com/bangbangbwa/backend/domain/sns/exception/NotFoundPostOrPermissionException.java
- src/main/java/com/bangbangbwa/backend/domain/sns/exception/type/PostErrorType.java
- src/main/java/com/bangbangbwa/backend/domain/sns/repository/PostRepository.java
- src/main/resources/mybatis/map/post.xml
- src/test/java/com/bangbangbwa/backend/domain/member/MemberTest.java
- src/test/java/com/bangbangbwa/backend/domain/sns/repository/PostRepositoryTest.java
- 게시물 고정 등록/삭제
- feature/BBB-111 -> dev
- 팔로우/언팔로우
- https://bangbangbwa.atlassian.net/jira/software/projects/BBB/boards/1?selectedIssue=BBB-111
> [BBB-111] 게시물 고정 등록/삭제

- src/main/java/com/bangbangbwa/backend/domain/member/business/FollowCreator.java
- src/main/java/com/bangbangbwa/backend/domain/member/business/FollowDeleter.java
- src/main/java/com/bangbangbwa/backend/domain/member/business/FollowGenerator.java
- src/main/java/com/bangbangbwa/backend/domain/member/business/FollowParser.java
- src/main/java/com/bangbangbwa/backend/domain/member/business/FollowUpdater.java
- src/main/java/com/bangbangbwa/backend/domain/member/common/dto/ToggleFollowDto.java
- src/main/java/com/bangbangbwa/backend/domain/member/common/entity/Follow.java
- src/main/java/com/bangbangbwa/backend/domain/member/common/mapper/FollowMapper.java
- src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberController.java
- src/main/java/com/bangbangbwa/backend/domain/member/exception/NotFoundFollowException.java
- src/main/java/com/bangbangbwa/backend/domain/member/exception/type/FollowErrorType.java
- src/main/java/com/bangbangbwa/backend/domain/member/repository/FollowRepository.java
- src/main/java/com/bangbangbwa/backend/domain/member/service/MemberService.java
- src/main/resources/mybatis/map/follow.xml
- src/main/resources/schema.sql
- src/test/java/com/bangbangbwa/backend/domain/member/MemberTest.java
- src/test/java/com/bangbangbwa/backend/domain/member/repository/FollowRepositoryTest.java
- 팔로우/언팔로우
- feature/BBB-112 -> dev
-
- https://bangbangbwa.atlassian.net/jira/software/projects/BBB/boards/1?selectedIssue=BBB-112
> [BBB-112] 팔로우/언팔로우

- src/main/java/com/bangbangbwa/backend/domain/admin/common/dto/GetReportedPostsDto.java
- src/main/java/com/bangbangbwa/backend/domain/admin/controller/AdminController.java
- src/main/java/com/bangbangbwa/backend/domain/admin/service/AdminService.java
- src/main/java/com/bangbangbwa/backend/domain/sns/business/ReportPostReader.java
- src/main/java/com/bangbangbwa/backend/domain/sns/common/dto/ReportPostDto.java
- src/main/java/com/bangbangbwa/backend/domain/sns/common/entity/ReportPost.java
- src/main/java/com/bangbangbwa/backend/domain/sns/common/mapper/ReportPostMapper.java
- src/main/java/com/bangbangbwa/backend/domain/sns/repository/ReportPostRepository.java
- src/main/resources/mybatis/map/reportPost.xml
- src/main/resources/schema.sql
- src/test/java/com/bangbangbwa/backend/domain/admin/controller/AdminTest.java
- src/test/java/com/bangbangbwa/backend/domain/sns/controller/SnsIntegrationTest.java
- src/test/java/com/bangbangbwa/backend/domain/sns/repository/ReportPostRepositoryTest.java
- src/test/java/com/bangbangbwa/backend/global/gson/LocalDateTimeAdapter.java
- src/test/java/com/bangbangbwa/backend/global/test/IntegrationTest.java
- report_posts 테이블 신고사유 컬럼 추가
- 게시물 신고시 신고사유 입력하도록 변경
- 신고된 게시물 조회
- gson을 이용해 LocalDateTime 직/역직렬화 중 문제 발생으로 LocalDateTimeAdapter 추가 및 적용
- feature/BBB-113 -> dev
-
- https://bangbangbwa.atlassian.net/jira/software/projects/BBB/boards/1?selectedIssue=BBB-113
> [BBB-113] 신고된 게시물 조회

- src/main/java/com/bangbangbwa/backend/domain/tag/common/dto/TagDto.java
- TagDto Mapping 시 오류 처리를 위해 추가
- feature/BBB-122 -> develop
- 플랫폼-스트리머 연결, 삭제
-
> [BBB-122] TagDto 생성자 수정

- build.gradle
- src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberController.java
- src/main/java/com/bangbangbwa/backend/domain/post/controller/PostController.java
- src/main/java/com/bangbangbwa/backend/domain/promotion/controller/PromotionController.java
- src/main/java/com/bangbangbwa/backend/domain/sns/controller/SnsController.java
- src/main/java/com/bangbangbwa/backend/domain/token/common/exception/AuthenticationRequiredException.java
- src/main/java/com/bangbangbwa/backend/domain/token/common/exception/type/TokenErrorType.java
- src/main/java/com/bangbangbwa/backend/domain/token/interceptor/AuthInterceptor.java
- src/main/java/com/bangbangbwa/backend/global/annotation/authentication/PermitAll.java
- src/test/java/com/bangbangbwa/backend/domain/member/MemberTest.java
- src/test/java/com/bangbangbwa/backend/domain/sns/controller/SnsIntegrationTest.java
- src/test/java/com/bangbangbwa/backend/global/test/RestTemplateConfig.java
- 인증/인가 리펙토링
- 회원/비회원 모두 접근 가능한 API에 PermitAll 어노테이션 추가
- feature/BBB-127 -> dev
-
- https://bangbangbwa.atlassian.net/jira/software/projects/BBB/boards/1?selectedIssue=BBB-127
> [BBB-127] 인증/인가 리펙토링

- src/main/java/com/bangbangbwa/backend/domain/comment/controller/CommentApi.java
- src/main/java/com/bangbangbwa/backend/domain/comment/controller/CommentController.java
- CommentController 문서화
- feature/BBB-128 -> dev
-
-
> [BBB-128] CommentController 문서화

- src/main/java/com/bangbangbwa/backend/domain/post/common/mapper/PostMapper.java
- src/test/java/com/bangbangbwa/backend/domain/post/PostIntegrationTest.java
- src/test/java/com/bangbangbwa/backend/domain/streamer/StreamerTest.java
- 게시물 목록 조회 미디어 여부 반환
- feature/BBB-133 -> dev
-
- https://bangbangbwa.atlassian.net/jira/software/projects/BBB/boards/1?selectedIssue=BBB-133
> [BBB-133] 게시물 목록 조회 미디어 여부 반환

- src/main/java/com/bangbangbwa/backend/domain/comment/business/CommentReader.java
- src/main/java/com/bangbangbwa/backend/domain/comment/service/CommentService.java
- src/main/java/com/bangbangbwa/backend/domain/post/business/PostReader.java
- src/main/java/com/bangbangbwa/backend/domain/post/common/dto/MyPostDto.java
- src/main/java/com/bangbangbwa/backend/domain/post/controller/PostApi.java
- src/main/java/com/bangbangbwa/backend/domain/post/controller/PostController.java
- src/main/java/com/bangbangbwa/backend/domain/post/service/PostService.java
- src/main/java/com/bangbangbwa/backend/domain/sns/repository/CommentRepository.java
- src/main/java/com/bangbangbwa/backend/domain/sns/repository/PostRepository.java
- src/main/java/com/bangbangbwa/backend/domain/streamer/repository/PostViewStreamerRepository.java
- src/main/resources/data.sql
- src/main/resources/mybatis/map/comment.xml
- src/main/resources/mybatis/map/post.xml
- src/main/resources/mybatis/map/postViewStreamer.xml
- 내 게시물 조회 API 구현
- 내 게시물 조회 API 문서화
- feature/BBB-132 -> develop
- 
-  https://bangbangbwa.atlassian.net/browse/BBB-132
> [BBB-132] 내 게시물 조회 API 구현

- src/main/java/com/bangbangbwa/backend/global/config/SecurityConfig.java
- src/main/java/com/bangbangbwa/backend/global/config/WebConfig.java
> [hotfix] CORS 설정 추가

- src/main/java/com/bangbangbwa/backend/global/config/SecurityConfig.java
> [hotfix] Method Security 설정 추가하기

- src/main/java/com/bangbangbwa/backend/global/config/SecurityConfig.java
> [hotfix] roleHierarchy 설정 추가

- src/main/java/com/bangbangbwa/backend/domain/post/controller/PostApi.java
- src/main/java/com/bangbangbwa/backend/domain/post/controller/PostController.java
> [doc] POST API 문서화 수정

- src/main/java/com/bangbangbwa/backend/domain/post/common/dto/MyPostDto.java
- src/main/resources/mybatis/map/postViewStreamer.xml
- 스트리머 닉네임 데이터 추가
- feature/BBB-132 -> dev
-
-
> [BBB-132] 스트리머 닉네임 데이터 추가

- src/main/java/com/bangbangbwa/backend/domain/comment/business/CommentReader.java
- src/main/java/com/bangbangbwa/backend/domain/comment/common/dto/MyCommentDto.java
- src/main/java/com/bangbangbwa/backend/domain/comment/service/CommentService.java
- src/main/java/com/bangbangbwa/backend/domain/member/common/dto/CommentDto.java
- src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberApi.java
- src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberController.java
- src/main/java/com/bangbangbwa/backend/domain/member/service/MemberService.java
- src/main/java/com/bangbangbwa/backend/domain/sns/repository/CommentRepository.java
- src/main/resources/mybatis/map/comment.xml
- src/test/java/com/bangbangbwa/backend/domain/member/controller/MemberControllerTest.java
- 내가 쓴 댓글 목록 조회 API 구현
- feature/BBB-137 -> dev
- 회원탈퇴 API 구
- https://bangbangbwa.atlassian.net/browse/BBB-135
> [BBB-137] 내가 쓴 댓글 목록 조회 API 구현

- src/main/java/com/bangbangbwa/backend/domain/member/common/entity/Member.java
- src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberApi.java
- src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberController.java
- src/main/java/com/bangbangbwa/backend/domain/member/service/MemberService.java
- src/main/java/com/bangbangbwa/backend/domain/platform/repository/StreamerPlatformRepository.java
- src/main/java/com/bangbangbwa/backend/domain/post/business/PostDeleter.java
- src/main/java/com/bangbangbwa/backend/domain/promotion/business/StreamerDeleter.java
- src/main/java/com/bangbangbwa/backend/domain/sns/repository/PostRepository.java
- src/main/java/com/bangbangbwa/backend/domain/streamer/repository/PostViewStreamerRepository.java
- src/main/java/com/bangbangbwa/backend/domain/tag/repository/StreamerTagRepository.java
- src/main/resources/mybatis/map/member.xml
- src/main/resources/mybatis/map/post.xml
- src/main/resources/mybatis/map/postViewStreamer.xml
- src/main/resources/mybatis/map/streamerPlatform.xml
- src/main/resources/mybatis/map/streamerTag.xml
- 회원탈퇴 API 구현
- feature/BBB-135 -> develop
-
-
> [BBB-135] 회원탈퇴 API 구현
